### ISSUE TITLE
Bug -- ImportError: cannot import name 'GraphMatchingModule'

### ISSUE THREAD

**Issue by GabbySuwichaya** [martius-lab/blackbox-deep-graph-matching#2]
Could you please help with this bug ....? 

I have received the following error: 

```
File "train_eval.py", line 12, in <module>
    from BB_GM.model import Net
  File "/mnt/HDD4TB3/blackbox-deep-graph-matching/BB_GM/model.py", line 6, in <module>
    from lpmp_py import GraphMatchingModule
ImportError: cannot import name 'GraphMatchingModule'
```

Although this may not come from your script; however, I also noticed that `lpmp_py` does not seem to have `GraphMatchingModule` as well...  

```
>>> import lpmp_py
>>> dir(lpmp_py)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'lpd', 'torch', 'torch_wrappers']

```
This is just indicating that the repo or the original  `lpmp` are having problems...

**Comment by rogerwwww** [comment]
This issue shall be caused by this commit https://github.com/mrolinek/LPMP/commit/0b73077d1db77f2146c1bac0adb8218dcb64b68d

Dear authors could you please resolve this issue? @dominikzietlow

**Comment by dominikzietlow** [comment]
Hi! Apologies for the delayed response to the original issue.
I've just updated the Pipfile, please try installing and running it again (tested it and it works for me).

**Comment by GabbySuwichaya** [comment]
Hi @dominikzietlow .... 
I still somehow get the error for installing  lpmp_py .... 
So, I did it manually .... by using 

`python3 -m pip install git+https://github.com/lpmp/LPMP.git`

However, I still get the following error: 

![Screenshot from 2021-01-07 23-57-07](https://user-images.githubusercontent.com/49115268/103907097-2bd5f400-5144-11eb-99e2-1248eaa453b9.png)

**Comment by dominikzietlow** [comment]
gcc-9 and g++-9 are installed? This looks like a local error to me though.
If this can not be resolved, I would like to ask you to raise an issue at the lpmp repository.

**Comment by georgmartius** [comment]
You get a permission denied error. Try --user
python3 -m pip install --user ....

**Comment by GabbySuwichaya** [comment]
@dominikzietlow  .... Yes, I have `gcc` and `g++`... Both are in version 9.3
@georgmartius  ..... I tried .... it does not solve ..... Actually, the error is similar ...

The full errors are as follows:

```
(Blackbox) gabby-suwichaya@gabby-suwichaya:/mnt/HDD4TB3/blackbox-deep-graph-matching$ python3 -m pip install --user git+https://github.com/lpmp/LPMP.git
Collecting git+https://github.com/lpmp/LPMP.git
  Cloning https://github.com/lpmp/LPMP.git to /tmp/pip-req-build-ldhlw0wy
Building wheels for collected packages: lpmp-py
  Building wheel for lpmp-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/gabby-suwichaya/anaconda3/envs/Blackbox/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ldhlw0wy/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ldhlw0wy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_fyayuif
       cwd: /tmp/pip-req-build-ldhlw0wy/
  Complete output (59 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/lpmp_py
  copying lpmp_py/__init__.py -> build/lib.linux-x86_64-3.6/lpmp_py
  copying lpmp_py/raw_solvers.py -> build/lib.linux-x86_64-3.6/lpmp_py
  creating build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
  copying lpmp_py/torch_wrappers/utils.py -> build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
  copying lpmp_py/torch_wrappers/__init__.py -> build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
  copying lpmp_py/torch_wrappers/multigraph_matching.py -> build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
  copying lpmp_py/torch_wrappers/graph_matching.py -> build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
  running build_ext
  Traceback (most recent call last):
    File "/usr/local/bin/cmake", line 11, in <module>
      load_entry_point('cmake==3.18.4.post1', 'console_scripts', 'cmake')()
    File "/usr/local/lib/python3.8/dist-packages/cmake-3.18.4.post1-py3.8-linux-x86_64.egg/cmake/__init__.py", line 46, in cmake
      raise SystemExit(_program('cmake', sys.argv[1:]))
    File "/usr/local/lib/python3.8/dist-packages/cmake-3.18.4.post1-py3.8-linux-x86_64.egg/cmake/__init__.py", line 42, in _program
      return subprocess.call([os.path.join(CMAKE_BIN_DIR, name)] + args)
    File "/usr/lib/python3.8/subprocess.py", line 340, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/cmake-3.18.4.post1-py3.8-linux-x86_64.egg/cmake/data/bin/cmake'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-ldhlw0wy/setup.py", line 123, in <module>
      zip_safe=False,
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-ldhlw0wy/setup.py", line 22, in run
      out = subprocess.check_output(['cmake', '--version'])
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/subprocess.py", line 438, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for lpmp-py
  Running setup.py clean for lpmp-py
Failed to build lpmp-py
Installing collected packages: lpmp-py
    Running setup.py install for lpmp-py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/gabby-suwichaya/anaconda3/envs/Blackbox/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ldhlw0wy/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ldhlw0wy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vn0b4ztd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/gabby-suwichaya/.local/include/python3.6m/lpmp-py
         cwd: /tmp/pip-req-build-ldhlw0wy/
    Complete output (61 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/lpmp_py
    copying lpmp_py/__init__.py -> build/lib.linux-x86_64-3.6/lpmp_py
    copying lpmp_py/raw_solvers.py -> build/lib.linux-x86_64-3.6/lpmp_py
    creating build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
    copying lpmp_py/torch_wrappers/utils.py -> build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
    copying lpmp_py/torch_wrappers/__init__.py -> build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
    copying lpmp_py/torch_wrappers/multigraph_matching.py -> build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
    copying lpmp_py/torch_wrappers/graph_matching.py -> build/lib.linux-x86_64-3.6/lpmp_py/torch_wrappers
    running build_ext
    Traceback (most recent call last):
      File "/usr/local/bin/cmake", line 11, in <module>
        load_entry_point('cmake==3.18.4.post1', 'console_scripts', 'cmake')()
      File "/usr/local/lib/python3.8/dist-packages/cmake-3.18.4.post1-py3.8-linux-x86_64.egg/cmake/__init__.py", line 46, in cmake
        raise SystemExit(_program('cmake', sys.argv[1:]))
      File "/usr/local/lib/python3.8/dist-packages/cmake-3.18.4.post1-py3.8-linux-x86_64.egg/cmake/__init__.py", line 42, in _program
        return subprocess.call([os.path.join(CMAKE_BIN_DIR, name)] + args)
      File "/usr/lib/python3.8/subprocess.py", line 340, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/cmake-3.18.4.post1-py3.8-linux-x86_64.egg/cmake/data/bin/cmake'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ldhlw0wy/setup.py", line 123, in <module>
        zip_safe=False,
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-ldhlw0wy/setup.py", line 22, in run
        out = subprocess.check_output(['cmake', '--version'])
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/home/gabby-suwichaya/anaconda3/envs/Blackbox/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/gabby-suwichaya/anaconda3/envs/Blackbox/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ldhlw0wy/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ldhlw0wy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vn0b4ztd/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/gabby-suwichaya/.local/include/python3.6m/lpmp-py Check the logs for full command output.
```

**Comment by dominikzietlow** [comment]
Not sure it's helping, but I find it puzzling that your anaconda env (btw: please try installing the pipenv as described in the readme) seems to run on python 3.6 but there's some inconsistency with python 3.8 in your logs.

**Comment by GabbySuwichaya** [comment]
Hi @dominikzietlow. Yes, you are right I could solve the problem now!.... 

So, I have deactivated all the conda environment, and install Pipenv. 
Actually, after I installed Pipfile with `pipenv install`, I get some error from Pytorch Geometry for the clustering package... However, I solved the problem by removing the previously installed Pytorch and Pytorch Geometry. Then, I have manually installed all of them with `pip` after activating the Pipenv in the directory.  

However, I get an error after test running the script with ...

`python3 train_eval.py experiments/voc_basic.json`, 

Could you please continue _helping me_? 

I got the following error: 

```
...
The following error happened after some iterations of data sampling and training ....
...
3 0 1 4 2 
4 3 1 0 2 
1 8 7 5 0 2 4 3 6 
5 2 4 3 1 0 
3 0 8 7 5 4 6 2 1 
2 3 4 1 0 
1 0 
2 6 5 4 0 1 3 
2 0 5 1 4 3 
4 5 1 0 7 6 3 2 
0 1 4 2 3 
1 3 0 2 
1 3 4 5 0 2 
1 3 4 5 0 2 
1 3 0 2 
3 2 4 1 0 
1 5 4 0 7 6 3 2 
3 0 1 5 4 2 
2 1 0 4 5 6 3 
0 1 
2 4 1 3 0 

...
Epoch 0    Iter 2000 34.60sample/s Loss=5.4750   Accuracy=0.59 F1=0.59
Over whole epoch 0    -------- Loss: 7.7024 Accuracy: 0.447 F1: 0.447

Start evaluation...

6 1 4 10 2 5 7 8 9 3 0 
6 1 4 10 2 5 7 8 9 3 0 
6 1 4 10 2 5 7 8 9 3 0 
6 1 4 10 2 5 7 8 9 3 0 
6 1 4 10 2 5 7 8 9 3 0 
6 1 4 10 2 5 7 8 9 3 0 
6 1 4 10 2 5 7 8 9 3 0 
Traceback (most recent call last):
  File "train_eval.py", line 248, in <module>
    start_epoch=0,
  File "train_eval.py", line 173, in train_eval_model
    accs, f1_scores = eval_model(model, dataloader["test"])
  File "/mnt/HDD4TB3/blackbox-deep-graph-matching/eval.py", line 67, in eval_model
    visualization_params=visualization_params,
  File "/home/gabby-suwichaya/.local/share/virtualenvs/blackbox-deep-graph-matching-1jjtHtx2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/HDD4TB3/blackbox-deep-graph-matching/BB_GM/model.py", line 136, in forward
    **visualization_params,
  File "/mnt/HDD4TB3/blackbox-deep-graph-matching/utils/decorators.py", line 36, in __call__
    return self.func(*new_args, **new_kwargs)
  File "/mnt/HDD4TB3/blackbox-deep-graph-matching/utils/visualization.py", line 207, in easy_visualize
    true_graph=true_graph,
  File "/mnt/HDD4TB3/blackbox-deep-graph-matching/utils/visualization.py", line 54, in visualize_graph
    connectionstyle="arc3,rad=0.2",
TypeError: draw_networkx_edges() got an unexpected keyword argument 'linewidths'
```

**Comment by dominikzietlow** [comment]
Looking into it.
If you quickly want to proceed, please remove the line that's responsible for the error (line #46 in visualization.py):
            linewidths=1,
that parameter might be obsolete.

**Comment by GabbySuwichaya** [comment]
Hi @dominikzietlow, Thanks...yes, I have to comment  `linewidths=1`  out  (line #46 in visualization.py)... 
Also, I have also commented `with_labels=False,` out (line #53 in visualization.py)... as I have received a similar error...

However, though the training seems working, it has been staying at the following step (shown below) for a while now (3-4 hours ago)... Is this normal? Could you explain why? 

By the way, I still used the sam execution function `python3 train_eval.py experiments/voc_basic.json`... to test running... 


```
1 3 0 2 
3 2 4 1 0 
1 5 4 0 7 6 3 2 
3 0 1 5 4 2 
2 1 0 4 5 6 3 
0 1 
2 4 1 3 0 
Epoch 0    Iter 2000 29.12sample/s Loss=5.7000   Accuracy=0.575 F1=0.575
Over whole epoch 0    -------- Loss: 7.6894 Accuracy: 0.447 F1: 0.448

Start evaluation...
3 6 1 2 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
3 6 2 1 8 7 4 5 0 
5 0 6 3 8 4 2 7 9 1 
5 0 6 3 8 2 1 4 9 7 
7 0 6 3 8 2 5 4 9 1 
1 0 6 3 8 2 5 4 9 7 
1 0 6 3 8 2 5 4 9 7 
1 0 6 3 8 2 5 4 9 7 
1 0 6 3 8 2 5 4 9 7 
1 0 6 3 8 2 5 4 9 7 
1 0 4 3 8 2 5 6 9 7 
1 0 6 3 8 2 5 4 9 7 
1 0 6 3 8 2 5 4 9 7 
0 5 7 1 3 6 4 2 8 
0 5 7 1 3 6 2 4 8 
0 5 7 1 3 6 2 4 8 
0 5 7 1 3 6 4 2 8 
0 5 7 1 3 6 4 2 8 
0 5 7 1 3 6 2 4 8 
0 5 7 1 3 6 2 4 8 
0 5 7 1 3 6 2 4 8 
0 5 7 1 3 6 2 4 8 
0 5 7 1 3 6 2 4 8 
0 5 7 1 3 6 2 4 8 
9 2 8 5 1 7 0 4 3 6 
9 6 8 5 1 7 0 2 4 3 
9 6 8 5 1 7 0 2 4 3 
9 6 8 5 1 7 0 2 4 3 
9 6 8 5 1 7 0 2 4 3 
9 6 8 5 1 7 0 2 4 3 
9 6 8 5 1 7 0 2 4 3 
9 6 8 5 1 4 0 2 7 3 
9 6 8 5 1 4 0 2 7 3 
9 6 8 5 1 4 0 2 7 3 
9 6 8 5 1 4 0 2 7 3 
0 1 4 3 2 
1 4 3 10 7 5 8 0 9 2 6 
7 0 3 10 6 4 8 1 9 2 5 
7 0 3 10 6 4 8 1 9 2 5 
8 0 3 10 7 4 6 1 9 2 5 
8 0 3 10 7 4 6 1 9 2 5 
8 0 3 10 7 4 6 1 9 2 5 
8 0 3 10 7 4 6 1 9 2 5 
8 0 3 10 7 4 6 1 9 2 5 
7 0 3 10 6 4 8 1 9 2 5 
8 0 3 10 7 4 6 1 9 2 5 
7 0 3 10 6 4 8 1 9 2 5 
5 1 7 3 2 6 0 4 
5 1 7 3 2 6 0 4 
5 1 7 3 2 6 0 4 
5 6 7 3 2 1 0 4 
5 6 7 3 2 1 0 4 
5 6 7 3 2 1 0 4 
5 6 7 3 2 1 0 4 
5 6 7 3 2 1 0 4 
5 6 7 3 2 1 0 4 
5 6 7 3 2 1 0 4 
5 6 7 3 2 1 0 4 
3 10 4 1 8 9 7 6 5 2 0 
3 10 4 1 8 9 7 6 5 2 0 
4 10 3 1 8 9 7 2 5 6 0 
4 10 3 1 8 9 7 2 5 6 0 
4 10 3 1 8 9 7 2 5 6 0 
4 10 3 1 8 9 7 2 5 6 0 
4 10 3 1 8 9 7 2 5 6 0 
4 10 3 1 8 9 7 2 5 6 0 
4 10 3 1 8 9 7 2 5 6 0 
4 10 3 1 8 9 7 2 5 6 0 
4 10 3 1 8 9 7 2 5 6 0  (It has been staying in this line for a while... Is this normal ? Could you explain why? )

```

**Comment by dominikzietlow** [comment]
Hi again!

Hm, I can not reproduce this behavior. I am past epoch 3 now after something like 2 hours.
Are you sure it's running on the GPU as intended?

I wish I could help you more at this moment.

**Comment by GabbySuwichaya** [comment]
Hi @dominikzietlow, I forget to update; I have just figured it out about 5 hours ago, but the code is just finished running. I am so sorry... I will close the issue now... 

So, thank you very much... You have been very helpful to me... I will refer to your work properly and provide the citations to all the related packages from your group...

Nevertheless, I think it is nice to just let you know my fix to this problem. 

-  One of the problems is that my computer doesn't have   the `texlive-latex-extra` package .... that is a reason why it stucked :

```
sudo apt-get install texlive-latex-extra
```

-  Also, before I found the fix above ...... I also change the following .... 

Instead of using `run` in [Line 75 utils/latex_utils.py](https://github.com/martius-lab/blackbox-deep-graph-matching/blob/master/utils/latex_utils.py#L75) ..... I have replaced it with `call` and yes I also have to import `call` via `from subprocess import call, PIPE`... 

I have modified the line to something like : 

```
call(['pdflatex', latex_file], cwd=tmpdir) 
```

Reference: https://stackoverflow.com/questions/7067210/why-doesnt-pdflatex-work-when-called-as-a-python-subprocess

**Comment by dominikzietlow** [comment]
Perfect! I am happy to hear that you made it work! :-) I will add the texlive package to the requirements in the README, it must have slipped our attention.
